spring:
  application:
    name: BizFlow-Admin
  
  # Cấu hình kết nối Database MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/bizflow_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root        # Thay bằng username MySQL (thường là root)
    password: 12345 # Thay bằng mật khẩu MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Cấu hình Hibernate / JPA
  jpa:
    hibernate:
      ddl-auto: update    # Tự động tạo/cập nhật bảng dựa trên Entity Java
    show-sql: true        # Hiển thị các câu lệnh SQL dưới console để dễ theo dõi
    properties:
      hibernate:
        format_sql: true  # Làm đẹp câu lệnh SQL trong console
        dialect: org.hibernate.dialect.MySQLDialect

# Cấu hình cổng chạy ứng dụng (Mặc định là 8080)
server:
  port: 8080